#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : faultstat
Version  : 0.01.10
Release  : 1
URL      : https://github.com/ColinIanKing/faultstat/archive/refs/tags/V0.01.10.tar.gz
Source0  : https://github.com/ColinIanKing/faultstat/archive/refs/tags/V0.01.10.tar.gz
Summary  : Page fault monitoring tool
Group    : Development/Tools
License  : GPL-2.0 LGPL-3.0+
Requires: faultstat-bin = %{version}-%{release}
Requires: faultstat-data = %{version}-%{release}
Requires: faultstat-license = %{version}-%{release}
Requires: faultstat-man = %{version}-%{release}
BuildRequires : pkgconfig(ncursesw)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Faultstat reports the page fault activity of processes
running on a system. The tool supports a 'top' like mode
to dynamically display the top page faulting processes.

%package bin
Summary: bin components for the faultstat package.
Group: Binaries
Requires: faultstat-data = %{version}-%{release}
Requires: faultstat-license = %{version}-%{release}

%description bin
bin components for the faultstat package.


%package data
Summary: data components for the faultstat package.
Group: Data

%description data
data components for the faultstat package.


%package license
Summary: license components for the faultstat package.
Group: Default

%description license
license components for the faultstat package.


%package man
Summary: man components for the faultstat package.
Group: Default

%description man
man components for the faultstat package.


%prep
%setup -q -n faultstat-0.01.10
cd %{_builddir}/faultstat-0.01.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1688405204
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1688405204
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/faultstat
cp %{_builddir}/faultstat-%{version}/COPYING %{buildroot}/usr/share/package-licenses/faultstat/4cc77b90af91e615a64ae04893fdffa7939db84c || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/faultstat

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/faultstat

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/faultstat/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/faultstat.8.gz
